static_offset: # Leaves the tag facing toward and offset from the OptiTrack origin
  x: 0
  y: 0
  z: 0
  roll: 1.571
  pitch: 0
  yaw: 1.571

apriltags:
  - family: 36h11
    tags:
    # - id: 51
    #   x: 0.914
    #   y: 2.438
    #   z: -1.19
    #   roll: 0
    #   pitch: 0
    #   yaw: 0
    #   frame_id: '/map'

    # - id: 50
    #   x: 2.743
    #   y: 2.438
    #   z: -1.52
    #   roll: 0
    #   pitch: 0
    #   yaw: 0
    #   frame_id: '/map'

    # - id: 49
    #   x: 4.572
    #   y: 2.438
    #   z: -1.5
    #   roll: 0
    #   pitch: 0
    #   yaw: 0
    #   frame_id: '/map'

    # - id: 47
    #   x: 6.401
    #   y: 2.438
    #   z: -1.47
    #   roll: 0
    #   pitch: 0
    #   yaw: 0
    #   frame_id: '/map'

    # - id: 46
    #   x: 8.229
    #   y: 2.438
    #   z: -1.55
    #   roll: 0
    #   pitch: 0
    #   yaw: 0
    #   frame_id: '/map'

    # - id: 45
    #   x: 10.058
    #   y: 2.438
    #   z: -1.57
    #   roll: 0
    #   pitch: 0
    #   yaw: 0
    #   frame_id: '/map'

    - id: 3
      x: 0
      y: -2
      z: 1.455
      roll: 0
      pitch: 0
      yaw: -0.05
      frame_id: '/map'

    - id: 4
      x: 0
      y: 0
      z: 1.45
      roll: 0
      pitch: 0
      yaw: 0
      frame_id: '/map'
    
    - id: 5
      x: 0
      y: 2
      z: 1.45
      roll: 0
      pitch: 0
      yaw: 0.05
      frame_id: '/map'