image_width: 2592
image_height: 1944
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [1902.80471,    0.     , 1280.61434,
            0.     , 1902.9521 ,  993.98548,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.306470, 0.108102, -0.002143, 0.008210, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [1609.94653,    0.     , 1315.31821,    0.     ,
            0.     , 1740.67102,  993.19924,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]
